# Lines that begin with a '#' are comments. No need to edit them.
[ERP]
address = "http://10.2.102.21:9000"  # intranet
# address = "https://erp.bits-pilani.ac.in:4431"  # internet

[ERP.CREDS]
username = "41120170069"
password = "password"

[MOODLE]
address = "https://td.bits-hyderabad.ac.in/moodle"
wstoken = "368b0c8b11dce69420ca42ef45bdd1dc"  # Copy Moodle Mobile Web Service Key from Preferences -> Security Keys

[DATES]  # this section needs to be manually updated from Timetable every sem
last_date = 2019-11-29  # last working date of the semester
midsem.start = 2019-09-28  # should be official date, to ensure correct holidays
midsem.end = 2019-10-05
holidays = [2019-08-12, 2019-08-15, 2019-08-24, 2019-09-02, 2019-10-02, 2019-10-08, 2019-10-26, 2019-11-12]
day_change = {2019-08-16 = "MO", 2019-10-09 = "SA", 2019-10-17 = "SA", 2019-11-01 = "MO"}
# means, Monday's timetable will be followed on 16 Aug and 1st Nov, Saturday's timetable on 9th and 17th Oct
# day values should be one of: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA']

[COURSES]
tt_file = 'path/to/TIMETABLE 1ST SEM 2019-20.xlsx'  # path to excel/json file of timetable. Use single quotes
midsem_file = 'path/to/midsem TIMETABLE I SEM 2019-20.csv'  # skip if you already have the JSON file.
whitelist = {}
overrides = {}
# whitelist = {"IS F341" = ["L", "P"], "CS F211" = ["P"]}  # only these courses will be processed in calendar. Set as {} to process all.
# overrides = {"IS F341" = {"L" = "L1", "P" = "P2"}}  # Set as {} to not make changes to the erp courses you've registered to. Should only contain courses inside whitelist if defined.
