# Lines that begin with a '#' are comments. No need to edit them.
[ERP]
address = "http://10.2.102.21:9000"  # intranet
# address = "https://erp.bits-pilani.ac.in:4431"  # internet

[ERP.CREDS]
username = "42020170069"
password = "password"

[MOODLE]
address = "https://td.bits-hyderabad.ac.in/moodle"
wstoken = "368b0c8b11dce69420ca42ef45bdd1dc"  # Copy Moodle Mobile Web Service Key from Preferences -> Security Keys

[DATES]  # this section needs to be manually updated from Timetable every sem
last_date = 2020-04-29  # last working date of the semester
midsem.start = 2020-03-02  # should be official date, to ensure correct holidays
midsem.end = 2020-03-07
holidays = [2020-01-15, 2020-01-26, 2020-01-29, 2020-03-10, 2020-03-20, 2020-03-21, 2020-03-25, 2020-04-02, 2020-04-06, 2020-04-10]
day_change = {2020-02-29 = "FR", 2020-03-19 = "SA", 2020-03-31 = "MO"}
# means, Friday's timetable will be followed on 29 Feb, Saturday's timetable on 19th Mar, etc.
# day values should be one of: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA']

[COURSES]
tt_file = 'path/to/Timetable II Sem 2019-20.xlsx'  # path to excel/json file of timetable. Use single quotes
midsem_file = 'path/to/midsem Timetable II Sem 2019-20.xlsx'  # skip if you already have the JSON file.
whitelist = {}
overrides = {}
# whitelist = {"IS F341" = ["L", "P"], "CS F211" = ["P"]}  # only these courses will be processed in calendar. Set as {} to process all.
# overrides = {"IS F341" = {"L" = "L1", "P" = "P2"}}  # Set as {} to not make changes to the erp courses you've registered to. Should only contain courses inside whitelist if defined.
