[ERP]
address = "http://10.2.102.21:9000"  # intranet
# address = "https://erp.bits-pilani.ac.in:4431"  # internet

[ERP.CREDS]
username = "41120170069"
password = "password"

[MOODLE]
address = "https://td.bits-hyderabad.ac.in/moodle"
wstoken = "368b0c8b11dce69420ca42ef45bdd1dc"  # Copy Moodle Mobile Web Service Key from Preferences -> Security Keys

[DATES]
last_date = 2019-04-30
midsem.start = 2019-03-11
midsem.end = 2019-03-17

[COURSES]
tt_file = 'path/to/TIMETABLE 1ST SEM 2019-20.xlsx'
midsem_file = "TT/midsem TIMETABLE I SEM 2019-20.csv"
whitelist = {"IS F341" = ["L", "P"], "CS F211" = ["P"]}  # only these courses will be processed in calendar. Set as {} to process all.
overrides = {"IS F341" = {"L" = "L1", "P" = "P2"}}  # should only contain courses inside whitelist if defined
